spring.application.name=sentiment-analysis-dashboard
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sentiment_dashboard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Properties
jwt.secret=94f27be08d95123d4c38217eeca292df283f5d5edc4936d5d5b746d88b0a9bd0
jwt.expiration=86400000

# Error Handling Fix for Spring Security
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
